import { WordItem, WordLevel } from '../types';

/**
 * Raw connectors list
 */
export const RAW_CONNECTORS_LIST = [
  { word: 'once', meaning: '-ınca, -ır -ımaz', subcategory: 'zaman (time)' },
  { word: 'when', meaning: '-dığında, -dığı zaman', subcategory: 'zaman (time)' },
  { word: 'while', meaning: '-iken, -e karşın', subcategory: 'zaman / zıtlık' },
  { word: 'after', meaning: '-dan sonra', subcategory: 'zaman (time)' },
  { word: 'before', meaning: '-meden önce', subcategory: 'zaman (time)' },
  { word: 'as soon as', meaning: '-ır -ırmaz', subcategory: 'zaman (time)' },
  { word: 'until / till', meaning: '-e kadar', subcategory: 'zaman (time)' },
  { word: 'by the time', meaning: '-dığında / -e kadar', subcategory: 'zaman (time)' },
  { word: 'since', meaning: '-den beri / -dığı için', subcategory: 'zaman / sebep' },
  { word: 'the moment (that)', meaning: '-dığı anda', subcategory: 'zaman (time)' },
  { word: 'every time', meaning: 'her oluşunda', subcategory: 'zaman (time)' },
  { word: 'no sooner…than', meaning: 'daha yeni –mıştı ki', subcategory: 'zaman (time)' },
  { word: 'hardly / scarcely / barely…when', meaning: 'daha yeni –mıştı ki', subcategory: 'zaman (time)' },
  { word: 'afterwards', meaning: 'daha sonra', subcategory: 'zaman (time)' },
  { word: 'during / at that time', meaning: 'o/bu esnada', subcategory: 'zaman (time)' },
  { word: 'in the meantime / meanwhile', meaning: 'bu arada', subcategory: 'zaman (time)' },
  { word: 'subsequently', meaning: 'daha sonra', subcategory: 'zaman (time)' },
  { word: 'then', meaning: 'daha sonra, o zaman', subcategory: 'zaman (time)' },
  { word: 'as if / as though', meaning: '-mış gibi', subcategory: 'benzetme / şekil' },
  { word: '(just/much) as', meaning: '-dığı gibi', subcategory: 'benzetme / şekil' },
  { word: '(in) the way (that)', meaning: '-dığı gibi / şekilde / biçimde', subcategory: 'benzetme / şekil' },
  { word: 'because', meaning: '-dığı için', subcategory: 'sebep (cause)' },
  { word: 'on account of the fact that', meaning: '-dığı için', subcategory: 'sebep (cause)' },
  { word: 'owing to the fact that', meaning: '-dığı için', subcategory: 'sebep (cause)' },
  { word: 'due to the fact that', meaning: '-dığı için', subcategory: 'sebep (cause)' },
  { word: 'for', meaning: 'çünkü', subcategory: 'sebep (cause)' },
  { word: 'now (that)', meaning: '-dığına göre', subcategory: 'sebep (cause)' },
  { word: 'on (the) grounds that', meaning: '-dığı gerekçesiyle', subcategory: 'sebep (cause)' },
  { word: 'in that', meaning: '-mesi açısından', subcategory: 'sebep (cause)' },
  { word: 'seeing that', meaning: '-dığı için', subcategory: 'sebep (cause)' },
  { word: 'given (that)', meaning: '-mesi göz önüne alınırsa', subcategory: 'sebep (cause)' },
  { word: 'considering (that)', meaning: '-mesi göz önüne alınırsa', subcategory: 'sebep (cause)' },
  { word: 'because of', meaning: '-den dolayı / nedeniyle / yüzünden', subcategory: 'sebep (cause)' },
  { word: 'due to', meaning: '-den dolayı / nedeniyle', subcategory: 'sebep (cause)' },
  { word: 'owing to', meaning: '-den dolayı / nedeniyle', subcategory: 'sebep (cause)' },
  { word: 'thanks to', meaning: '-nin sayesinde', subcategory: 'sebep (cause)' },
  { word: 'in view of / on account of', meaning: 'nedeniyle', subcategory: 'sebep (cause)' },
  { word: 'although', meaning: '-e rağmen / -se de', subcategory: 'zıtlık (contrast)' },
  { word: 'though', meaning: '-e rağmen / -se de', subcategory: 'zıtlık (contrast)' },
  { word: 'even though', meaning: '-e rağmen / -se de', subcategory: 'zıtlık (contrast)' },
  { word: 'despite the fact that', meaning: '-e rağmen / -se de', subcategory: 'zıtlık (contrast)' },
  { word: 'in spite of the fact that', meaning: '-e rağmen / -se de', subcategory: 'zıtlık (contrast)' },
  { word: 'whereas', meaning: '-e karşın / -se de', subcategory: 'zıtlık (contrast)' },
  { word: 'whether…or…', meaning: 'ister… isterse…', subcategory: 'zıtlık (contrast)' },
  { word: 'despite', meaning: '-e rağmen', subcategory: 'zıtlık (contrast)' },
  { word: 'in spite of', meaning: '-e rağmen', subcategory: 'zıtlık (contrast)' },
  { word: 'notwithstanding', meaning: '-e rağmen', subcategory: 'zıtlık (contrast)' },
  { word: 'unlike', meaning: '-nin aksine / tersine', subcategory: 'zıtlık (contrast)' },
  { word: 'in contrast to', meaning: '-nın aksine', subcategory: 'zıtlık (contrast)' },
  { word: 'contrary to', meaning: '-nın tersine', subcategory: 'zıtlık (contrast)' },
  { word: 'as opposed to', meaning: '-e karşı olarak', subcategory: 'zıtlık (contrast)' },
  { word: 'but', meaning: 'ama / fakat / ancak', subcategory: 'zıtlık (contrast)' },
  { word: 'nevertheless', meaning: 'yine de', subcategory: 'zıtlık (contrast)' },
  { word: 'nonetheless', meaning: 'yine de', subcategory: 'zıtlık (contrast)' },
  { word: 'however', meaning: 'ancak / fakat', subcategory: 'zıtlık (contrast)' },
  { word: 'yet', meaning: 'ama / yine de', subcategory: 'zıtlık (contrast)' },
  { word: 'even so', meaning: 'böyle olsa bile', subcategory: 'zıtlık (contrast)' },
  { word: 'still', meaning: 'yine de', subcategory: 'zıtlık (contrast)' },
  { word: 'in / by contrast', meaning: 'aksine / tersine', subcategory: 'zıtlık (contrast)' },
  { word: 'on the contrary', meaning: 'tam tersi', subcategory: 'zıtlık (contrast)' },
  { word: 'conversely', meaning: 'aksine / tersine', subcategory: 'zıtlık (contrast)' },
  { word: 'on the other hand', meaning: 'öte yandan', subcategory: 'zıtlık (contrast)' },
  { word: 'if', meaning: '-se / -sa', subcategory: 'koşul (condition)' },
  { word: 'provided / providing (that)', meaning: '-mesi koşuluyla', subcategory: 'koşul (condition)' },
  { word: 'even if / when / after / before', meaning: '-se / -dığında bile', subcategory: 'koşul (condition)' },
  { word: 'on (the) condition (that)', meaning: '-mesi şartıyla', subcategory: 'koşul (condition)' },
  { word: 'as long as / so long as', meaning: '-dığı sürece', subcategory: 'koşul (condition)' },
  { word: 'unless', meaning: '-mezse / -medikçe', subcategory: 'koşul (condition)' },
  { word: 'suppose(ing) (that)', meaning: 'diyelim ki', subcategory: 'koşul (condition)' },
  { word: 'imagine (that)', meaning: 'hayal et ki', subcategory: 'koşul (condition)' },
  { word: 'what if', meaning: 'ya … -se/-sa?', subcategory: 'koşul (condition)' },
  { word: 'in the event (that)', meaning: '-mesi durumunda', subcategory: 'koşul (condition)' },
  { word: 'except that', meaning: '-mesi dışında', subcategory: 'şerh' },
  { word: 'if only / wish', meaning: 'keşke', subcategory: 'beklenti / ihtimal' },
  { word: 'in case', meaning: '-ır diye / ihtimaline karşı', subcategory: 'beklenti / ihtimal' },
  { word: 'for fear that', meaning: '-eceği korkusuyla', subcategory: 'beklenti / ihtimal' },
  { word: 'so (that)', meaning: '-sin diye', subcategory: 'amaç (purpose)' },
  { word: 'in order that', meaning: '-mek için', subcategory: 'amaç (purpose)' },
  { word: 'in order (for …) to', meaning: '-mek için', subcategory: 'amaç (purpose)' },
  { word: 'so as to', meaning: '-mek için', subcategory: 'amaç (purpose)' },
  { word: 'to', meaning: '-mek için', subcategory: 'amaç (purpose)' },
  { word: 'for this purpose', meaning: 'bu amaçla', subcategory: 'amaç (purpose)' },
  { word: 'to this end', meaning: 'bu amaçla', subcategory: 'amaç (purpose)' },
  { word: 'where', meaning: '-dık yerde', subcategory: 'yer (place)' },
  { word: 'everywhere', meaning: '-dık her yerde', subcategory: 'yer (place)' },
  { word: 'so / such…that', meaning: 'o kadar… ki', subcategory: 'sonuç (result)' },
  { word: 'the comparative…, the comparative…', meaning: '...ne kadar… o kadar…', subcategory: 'sonuç (result)' },
  { word: 'as a consequence', meaning: 'bu yüzden', subcategory: 'sonuç (result)' },
  { word: 'as a result', meaning: 'sonuç olarak', subcategory: 'sonuç (result)' },
  { word: 'because of this', meaning: 'bu yüzden', subcategory: 'sonuç (result)' },
  { word: 'therefore', meaning: 'bu yüzden', subcategory: 'sonuç (result)' },
  { word: 'hence', meaning: 'bu yüzden', subcategory: 'sonuç (result)' },
  { word: 'that is why', meaning: 'bu yüzden', subcategory: 'sonuç (result)' },
  { word: 'thus', meaning: 'böylece', subcategory: 'sonuç (result)' },
  { word: 'accordingly', meaning: 'buna göre', subcategory: 'sonuç (result)' },
  { word: 'in turn', meaning: 'dolayısıyla', subcategory: 'sonuç (result)' },
  { word: 'in addition to', meaning: '-e ek olarak', subcategory: 'ek bilgi (addition)' },
  { word: 'apart from', meaning: '-den başka', subcategory: 'ek bilgi (addition)' },
  { word: 'aside from', meaning: '-den başka', subcategory: 'ek bilgi (addition)' },
  { word: 'along with', meaning: 'ile birlikte', subcategory: 'ek bilgi (addition)' },
  { word: 'as well as', meaning: '-nın yanı sıra', subcategory: 'ek bilgi (addition)' },
  { word: 'besides', meaning: '-den başka / ayrıca', subcategory: 'ek bilgi (addition)' },
  { word: 'furthermore', meaning: 'ayrıca', subcategory: 'ek bilgi (addition)' },
  { word: 'moreover', meaning: 'üstelik', subcategory: 'ek bilgi (addition)' },
  { word: 'what is more', meaning: 'dahası', subcategory: 'ek bilgi (addition)' },
  { word: 'for example', meaning: 'örneğin', subcategory: 'örnekleme (example)' },
  { word: 'for instance', meaning: 'örneğin', subcategory: 'örnekleme (example)' },
  { word: 'to illustrate', meaning: 'örneklemek için', subcategory: 'örnekleme (example)' },
  { word: 'namely', meaning: 'yani', subcategory: 'örnekleme (example)' },
  { word: 'in other words', meaning: 'diğer bir deyişle', subcategory: 'açıklama (explanation)' },
  { word: 'that is (to say)', meaning: 'yani', subcategory: 'açıklama (explanation)' },
  { word: 'in fact', meaning: 'aslında / hatta', subcategory: 'açıklama (explanation)' },
  { word: 'as a matter of fact', meaning: 'aslında', subcategory: 'açıklama (explanation)' },
  { word: 'in reality / practice', meaning: 'gerçekte / pratikte', subcategory: 'açıklama (explanation)' },
  { word: 'indeed', meaning: 'gerçekten de / hatta', subcategory: 'açıklama (explanation)' },
  { word: 'likewise', meaning: 'benzer şekilde', subcategory: 'benzerlik (similarity)' },
  { word: 'similarly', meaning: 'benzer şekilde', subcategory: 'benzerlik (similarity)' },
  { word: 'not only… but also', meaning: 'sadece … değil aynı zamanda …', subcategory: 'diğer yapılar' },
  { word: 'both…and', meaning: 'hem … hem de …', subcategory: 'diğer yapılar' },
  { word: 'either…or', meaning: 'ya … ya …', subcategory: 'diğer yapılar' },
  { word: 'neither…nor', meaning: 'ne … ne de …', subcategory: 'diğer yapılar' },
  { word: 'irrespective of / regardless of', meaning: '-e bakılmaksızın', subcategory: 'diğer yapılar' },
  { word: 'rather than', meaning: '-dense / -mektense', subcategory: 'diğer yapılar' },
  { word: 'instead of', meaning: '-nın yerine', subcategory: 'diğer yapılar' },
  { word: 'without', meaning: '-sız / -siz', subcategory: 'diğer yapılar' },
  { word: 'but for', meaning: 'olmasaydı', subcategory: 'diğer yapılar' },
  { word: 'overall', meaning: 'genelde / toplamda', subcategory: 'diğer yapılar' }
];

export const RAW_ETYMOLOGY_ROOTS = [
  { root: 'ab (away)', words: ['abnormal', 'abuse', 'abhor', 'abandon', 'abduct', 'abolish', 'absent', 'abort', 'abrupt', 'absurd', 'absolutely', 'abdicate', 'absorb', 'abrasive', 'aberrant', 'abstract', 'abstain', 'abject', 'aboriginal', 'abomination'] },
  { root: 'ad/af/a/ag (to, towards)', words: ['addict', 'admit', 'admire', 'advertise', 'adhere', 'adjust', 'adapt', 'adopt', 'adept', 'adventure', 'advisor', 'advice', 'advance', 'address', 'administer', 'adverse', 'advocate', 'adore', 'adorn', 'adult', 'lead', 'afford', 'aspire', 'paramount', 'allow', 'allocate', 'agent', 'agile', 'attention'] },
  { root: 'ambi, amphi (both, on both/all sides)', words: ['ambassador', 'ambidextrous', 'ambiguous', 'ambition', 'ambush', 'amphibian', 'ambiance', 'ambivalence', 'ambivert', 'ambilateral'] },
  { root: 'ant (before)', words: ['advance', 'advantage', 'antecedent', 'ancient', 'ancestor', 'anticipate', 'antique', 'until'] },
  { root: 'bi (two, twice)', words: ['biceps', 'bicycle', 'bipedal', 'bilingual', 'binoculars', 'bicentennial', 'bilateral', 'biannual', 'bisexual', 'bias', 'bigamy', 'combine', 'bipartisan', 'bipolar'] },
  { root: 'ced (go, move, give, yield)', words: ['access', 'cease', 'concede', 'deceased', 'exceed', 'intercede', 'precede', 'proceed', 'procedure', 'recede', 'recession', 'secede', 'succeed', 'supersede', 'unprecedented'] },
  { root: 'cept (taken, seized)', words: ['accept', 'contraceptive', 'encapsulate', 'except', 'exceptional', 'deception', 'perception', 'reception', 'intercept', 'concept', 'conceive', 'inception', 'susceptible', 'capture', 'capacity', 'cable', 'catch', 'chase', 'cater', 'occupy', 'anticipate', 'participate', 'recover', 'recuperate', 'emancipate'] },
  { root: 'cid/cis (cut, kill)', words: ['accident', 'cadaver', 'casualty', 'caesarean', 'chiselled', 'circumcise', 'coincidence', 'concise', 'decide', 'deciduous', 'excise', 'fungicide', 'genocide', 'herbicide', 'homicide', 'incident', 'incise', 'infanticide', 'insecticide', 'matricide', 'patricide', 'pesticide', 'precise', 'scissors', 'suicide'] },
  { root: 'clud/clus (shut, close)', words: ['close', 'claustrophobia', 'cluster', 'conclude', 'conclusive', 'disclose', 'exclude', 'exclusive', 'include', 'preclude', 'recluse', 'seclude'] },
  { root: 'co(l,m,n,r) (with, together, mutual)', words: ['accommodate', 'coalition', 'coherent', 'coincidence', 'collaborate', 'collapse', 'collect', 'collide', 'collocation', 'colony', 'combat', 'combination', 'combine', 'commemorate', 'commerce', 'committee', 'commitment', 'communicate', 'communicable', 'communal', 'companion', 'company', 'accompany', 'compare', 'compensate', 'compete', 'comply', 'compile', 'comprehend', 'compose', 'concerted', 'concord', 'conduct', 'confer', 'configuration', 'confront', 'congregate', 'connect', 'consensus', 'consistent', 'conspire', 'consult', 'constellation', 'constitute', 'continue', 'contract', 'contribute', 'convene', 'conversation', 'convert', 'coexist', 'confide', 'conform', 'cooperate', 'coordinate', 'correlation', 'correspond'] }
];
